//SCREEN CONSTANTS
export const SCREEN_HEIGHT = 667;
export const SCREEN_WIDTH = 375;

// STRING CONSTANTS
export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILED';
export const AUTH_TOKEN_KEY = 'AUTH_TOKEN_KEY';
export const USERNAME = 'USERNAME';
export const PASSWORD = 'PASSWORD';

export const RESET_SECTION_LIST = 'RESET_SECTION_LIST';
export const SECTION_LIST_SUCCESS = 'SECTION_LIST_SUCCESS';
export const SECTION_LIST_FAILED = 'SECTION_LIST_FAILED';

export const START_SPINNER = 'START_SPINNER';
export const STOP_SPINNER = 'STOP_SPINNER';